# -*- coding: utf-8 -*-
"""Copy of FakeNews_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-NvOYHblsWuGfw2KniqqWaRgqYiaHaP

# Fake News Project
This project contains two datasets, one of fake news and the other of real news.

This data was sourced from https://www.kaggle.com/clmentbisaillon/fake-and-real-news-dataset
"""

#@title Load your dataset
import pandas as pd
from sklearn.model_selection import train_test_split
import nltk
import spacy

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from spacy.lang.en.stop_words import STOP_WORDS
from nltk.corpus import wordnet as wn

from spacy.lang.en.stop_words import STOP_WORDS
import string

from sklearn.feature_extraction.text import CountVectorizer
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('omw-1.4') 

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
#!python -m spacy download en_core_web_md
text_to_nlp = spacy.load('en_core_web_md')

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense

import scipy.sparse
#!wget -q --show-progress "https://storage.googleapis.com/inspirit-ai-data-bucket-1/Data/AI%20%2B%20X/Group/Journalism/Fake%20News/fake_news_data.csv"
#!wget -q --show-progress "https://storage.googleapis.com/inspirit-ai-data-bucket-1/Data/AI%20%2B%20X/Group/Journalism/Fake%20News/true_news_data.csv"
fake_news_data = pd.read_csv('fake_news_data.csv')
true_news_data = pd.read_csv('true_news_data.csv')

#fake_news_data

#true_news_data

fake_news_data.shape[0] + true_news_data.shape[0]

true_news_data.dropna().shape

true_news_data_with_label = true_news_data.copy()
true_news_data_with_label['label'] = True
true_news_data_with_label.head()

fake_news_data_with_label = fake_news_data.copy()
fake_news_data_with_label['label'] = False
fake_news_data_with_label.head()

all_news_data_with_label = pd.concat([true_news_data_with_label,fake_news_data_with_label])
#all_news_data_with_label

all_news_data = all_news_data_with_label[['title','label']]
#all_news_data

X = all_news_data['title']
y = all_news_data['label']
X_train,X_test,y_train,y_test = train_test_split(X, y ,test_size = .2 , random_state = 42)

#y

tokenized_dataset = [word_tokenize(sentence) for sentence in all_news_data['title']]
#tokenized_dataset

def remove_STOP_WORDS(tokens):
  return [token for token in tokens if token.lower() not in STOP_WORDS]
tokenized_dataset = [remove_STOP_WORDS(tokens) for tokens in tokenized_dataset]
def remove_punctuation(tokens):
   return [token for token in tokens if token not in string.punctuation]
tokenized_dataset = [remove_punctuation(tokens) for tokens in tokenized_dataset]
#tokenized_dataset

lemmatizer = WordNetLemmatizer()
tokenized_dataset = [[lemmatizer.lemmatize(word) for word in sentence] for sentence in tokenized_dataset]
#tokenized_dataset

from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
count_vectors = [count_vectorizer.fit_transform(tokens) for tokens in tokenized_dataset]

matrix = pd.DataFrame()
matrix['title'] = [tokens for tokens in tokenized_dataset]
matrix['label'] = [label for label in y]

#matrix

X = matrix['title']
y = matrix['label']
X_train,X_test,y_train,y_test = train_test_split(X, y ,test_size = .2 , random_state = 42)

def tokenize(text):
    clean_tokens = []
    for token in text_to_nlp(text):
        if (not token.is_stop) & (token.lemma_ != '-PRON-') & (not token.is_punct): # -PRON- is a special all inclusive "lemma" spaCy uses for any pronoun, we want to exclude these
            clean_tokens.append(token.lemma_)
    return clean_tokens

X = X.apply(lambda x: " ".join(x))
#X

bow_transformer = CountVectorizer(analyzer=tokenize, max_features=800).fit(X)

import numpy as np

vocab = [""]*len(bow_transformer.vocabulary_)

for keys,val in bow_transformer.vocabulary_.items():
  vocab[val] = keys

print(vocab[799])

bow_transformer.vocabulary_.items()

vocab = pd.Series(vocab)
print(vocab)
vocab.to_csv("vocab.txt")

X_x = bow_transformer.transform(X)



pd.DataFrame(X_x.toarray()).to_csv("X_x.csv")

y.to_csv("y.csv")

X_train, X_test, y_train, y_test = train_test_split(X_x, y, test_size=0.2, random_state=101)

y.shape

logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

y_pred = logistic_model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print (accuracy)

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

mlp = MLPClassifier(hidden_layer_sizes=(3,4,6), random_state = 1, activation = 'relu')
mlp.fit(X_train,y_train)
y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)

print(accuracy)

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

real_data = [
  ["Amid Maui fire devastation, Big Oil tries to kill Hawaii climate lawsuit"],
  ["El Salvador’s model of authoritarianism may be spreading to countries like Costa Rica and Honduras"],
  ["The nonsensical ‘right and left need to unite to take on elites’ take that just won’t die"],
  ["Landmark rent stabilization bill shows how communities can fight the housing crisis"],
  ["Jujuy stands up against multinational mining companies and anti-democratic reforms"],
  ["Landmark rent stabilization bill shows how communities can fight the housing crisis"],
  ["On Israel and Palestine, public opinion is finally changing—when will US policy change with it?"],
  ["Juvenile sentencing in the US is barbaric, racist, and ineffective"],
  ["As 93 confirmed dead, locals fear Lahaina rebuild dominated by rich outsiders"],
  ["How liberal comedians became lap dogs for establishment power"],
  ["Niger is the fourth country in the Sahel to experience an anti-Western coup"],
  ["LA County sheriffs keep pulling people over for bogus reasons. This time they got caught"],
  ["How ‘urban renewal’ went from a vision for public good to a private enrichment scheme"],
  ["Trump decides to snub the first GOP debate in favor of an interview with Tucker Carlson"],
  ["Hurricane Hilary could bring record rainfall to parts of the Southwest"],
  ["Father of 20-year-old murdered by girlfriend in 100 mph crash doesn't want life in prison for her Ohio teen convicted "]]


fake_articles = [
  ["Conservatives Explain Why They Love 'Rich Men North Of Richmond' Singer Oliver Anthony"],
  ["Most Shocking Moments From The Roger Stone Tapes"]]



df = pd.DataFrame(data = real_data)
token_real = [word_tokenize(sentence) for sentence in df[0]]

def remove_STOP_WORDS(tokens):
  return [token for token in tokens if token.lower() not in STOP_WORDS]
token_real = [remove_STOP_WORDS(tokens) for tokens in token_real]

def remove_punctuation(tokens):
   return [token for token in tokens if token not in string.punctuation]

token_real = [remove_punctuation(tokens) for tokens in token_real]
token_real = [[lemmatizer.lemmatize(word) for word in sentence] for sentence in token_real]
real_matrix = pd.DataFrame()
real_matrix['titless'] = [tokenss for tokenss in token_real]

real = real_matrix['titless']
real = real.apply(lambda x: " ".join(x))

bw = CountVectorizer(analyzer = tokenize,max_features=800).fit(real)
real = bw.transform(real)

real_preds = mlp.predict(real)
real_preds

import tensorflow as tf
import seaborn as sns

X_test_dense = tf.sparse.to_dense(X_test)
type(X_test_dense)

def plot_acc(history, ax = None, xlabel = 'Epoch #'):
    history = history.history
    history.update({'epoch':list(range(len(history['val_accuracy'])))})
    history = pd.DataFrame.from_dict(history)

    best_epoch = history.sort_values(by = 'val_accuracy', ascending = False).iloc[0]['epoch']

    if not ax:
      f, ax = plt.subplots(1,1)
    sns.lineplot(x = 'epoch', y = 'val_accuracy', data = history, label = 'Validation', ax = ax)
    sns.lineplot(x = 'epoch', y = 'accuracy', data = history, label = 'Training', ax = ax)
    ax.axhline(0.5, linestyle = '--',color='red', label = 'Chance')
    ax.axvline(x = best_epoch, linestyle = '--', color = 'green', label = 'Best Epoch')
    ax.legend(loc = 7)
    ax.set_ylim([0.4, 1])

    ax.set_xlabel(xlabel)
    ax.set_ylabel('Accuracy (Fraction)')

    plt.show()

model = Sequential()
model.add(Dense(3, input_shape=(800,),activation = 'relu'))
model.add(Dense(4,activation = 'sigmoid'))
model.add(Dense(6,activation = 'sigmoid'))
model.add(Dense(1,activation = 'sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy',metrics = "accuracy")
X_train_dense = X_train.toarray()
X_test_dense = X_test.toarray()
history = model.fit(X_train_dense,y_train, epochs = 10,validation_data = (X_test_dense,y_test))

plot_acc(history)

history.history

y_pred = model.predict(X_test)

for i in range(len(y_pred)):
  if(y_pred[i] > .5):
    y_pred[i] = True
  else:
    y_pred[i] = False

cam = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cam,display_labels = ['true','fake'])
disp.plot()