# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M2ygPkha-DvK4gZRnJQ3GCGbXFCUkdn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense
from sklearn.feature_extraction.text import CountVectorizer

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets


import tensorflow as tf
import seaborn as sns

X_x = pd.read_csv("X_x.csv",index_col = 0)
y = pd.read_csv("y.csv",index_col = 0)

vocab = pd.read_csv("vocab.txt",index_col = 0,names = ["Words"],header = 0)

vocab.head()

X_train, X_test, y_train, y_test = train_test_split(X_x, y, test_size=0.2, random_state=101)

logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

negative_words = np.sort(logistic_model.coef_)[0,:5]
posotive_words = np.sort(logistic_model.coef_)[:,::-1][0,:5]
print(negative_words)
print(posotive_words)

logistic_model.coef_[0,:5]

pos_idx = np.argsort(logistic_model.coef_)[:,::-1][0,:10]
neg_idx = np.argsort(logistic_model.coef_)[0,:10]

pos_idx

neg_idx

vocab.Words[neg_idx]

vocab.Words[pos_idx]

type(vocab)

y_pred = logistic_model.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print (accuracy)

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)



cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

mlp = MLPClassifier(hidden_layer_sizes=(3,4,6), random_state = 1, activation = 'relu')
mlp.fit(X_train,y_train)
y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)

print(accuracy)

y_pred = mlp.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = ['true','fake'])
disp.plot()

def plot_acc(history, ax = None, xlabel = 'Epoch #'):
    history = history.history
    history.update({'epoch':list(range(len(history['val_accuracy'])))})
    history = pd.DataFrame.from_dict(history)

    best_epoch = history.sort_values(by = 'val_accuracy', ascending = False).iloc[0]['epoch']

    if not ax:
      f, ax = plt.subplots(1,1)
    sns.lineplot(x = 'epoch', y = 'val_accuracy', data = history, label = 'Validation', ax = ax)
    sns.lineplot(x = 'epoch', y = 'accuracy', data = history, label = 'Training', ax = ax)
    ax.axhline(0.5, linestyle = '--',color='red', label = 'Chance')
    ax.axvline(x = best_epoch, linestyle = '--', color = 'green', label = 'Best Epoch')
    ax.legend(loc = 7)
    ax.set_ylim([0.4, 1])

    ax.set_xlabel(xlabel)
    ax.set_ylabel('Accuracy (Fraction)')

    plt.show()

model = Sequential()
model.add(Dense(3, input_shape=(800,),activation = 'relu'))
model.add(Dense(4,activation = 'sigmoid'))
model.add(Dense(6,activation = 'sigmoid'))
model.add(Dense(1,activation = 'sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy',metrics = "accuracy")
#X_train_dense = X_train.toarray()
#X_test_dense = X_test.toarray()
history = model.fit(X_train,y_train, epochs = 10,validation_data = (X_test,y_test))

plot_acc(history)